# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ShakeFeedbackDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking', '~> 3.0.0'



end

  # Pods for ShakeFeedbackDemo

  target 'ShakeFeedbackDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShakeFeedbackDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end


